### ISSUE TITLE
What can I do to make ChromiumGtk support CEF 4430.212?

### ISSUE THREAD

**Issue by towerbit** [lunixo/ChromiumGtk#4]
Hi,
I have build a libcef.so with the source that "Update to Chromium version 90.0.4430.212" from [bitbuket](https://bitbucket.org/chromiumembedded/cef/branch/4430)  for H264 support. But it seems not working  with the latest ChromiumGtk at all.

Here is the error when I run "Lunixo.ChromiumGtk.Examples.Simple" after I replaced the original file with the one I build.
`
Unhandled exception. Xilium.CefGlue.CefVersionMismatchException: CEF runtime version mismatch: loaded version API hash "b227b3fdd6142a9d8ff0f2252a71425f15960800", but supported "66613a535ec6a1aafce6ece8e98cd3876f79633b" (90.5.4+gc6a4331+chromium-90.0.4430.72).
   at Xilium.CefGlue.CefRuntime.CheckVersionByApiHash()
   at Xilium.CefGlue.CefRuntime.CheckVersion()
   at Xilium.CefGlue.CefRuntime.Load(String path)
   at Xilium.CefGlue.CefRuntime.Load()
   at Lunixo.ChromiumGtk.Core.Runtime.Initialize(CefApp customApp)
   at Lunixo.ChromiumGtk.Examples.Simple.Program.Main()
Aborted (core dumped)
`

BTW: I use the command parameters such as "--branch=4430" for running "automate-git.py", is there any way can help me to get the version 4430.72 instead of 4430.212?

**Comment by dmsch** [comment]
Hi,

there is no compatible CefGlue version for this build (4430.212).

automate-git.py has a parameter to checkout the exact version (--checkout), but I have not tried this one yet.
https://bitbucket.org/chromiumembedded/cef/src/0fa40110e3e68f5ee68cd904191fa1398cf84ef2/tools/automate/automate-git.py#lines-639

**Comment by towerbit** [comment]
It's just what I need, Thanks a lot!
