### ISSUE TITLE
Can not input any thing in the WebView? 

### ISSUE THREAD

**Issue by towerbit** [lunixo/ChromiumGtk#5]
Hi,
Visit "www.google.com" with the "Lunixo.ChromiumGtk.Examples.Simple", but can type nothing into the seach box on the page by keyboard. 
However type words with the "cefsimple" program is OK.

Any suggestion will be appreciated.

BTW: ChromiumGtk is the best CEF wrapper for .net core on Linux platform as far as I know, Thank **dmsch** from the bottom of my heart.

**Comment by dmsch** [comment]
Hi,
unfortunately, this is a known bug in the Chromium Embedded Framework:
https://bitbucket.org/chromiumembedded/cef/issues/2026/multiple-major-keyboard-focus-issues-on

The only workaround I currently know is to create the GTK window as a popup:

```C#
var window = new Gtk.Window(WindowType.Popup)
{
    WidthRequest = 1200,
    HeightRequest = 800,
};
```

**Comment by towerbit** [comment]
Unfortunately, the popup mode window does not have a title bar.
Anyway, it dose work.
